using System.Diagnostics;

namespace SharpInference.Vulkan;

/// <summary>
/// Compiles GLSL compute shaders to SPIR-V. The published NativeAOT binary serves
/// every shipped shader from a committed, precompiled table (<see cref="ShadersPrecompiled"/>,
/// generated by tools/SpirvGen) so glslc is never invoked at runtime. Sources not in the
/// table (e.g. ad-hoc test shaders) fall back to shelling out to the Vulkan SDK's glslc.
/// Results are cached in-process.
/// </summary>
public static class ShaderCompiler
{
    // Keyed by the deterministic StableHash (not the per-process-randomized String.GetHashCode),
    // so an entry can be served from the precompiled table as well as the in-process cache.
    private static readonly Dictionary<ulong, byte[]> s_cache = new();

    /// <summary>
    /// Number of times <see cref="Compile"/> fell back to invoking glslc (i.e. a source was
    /// not found in the precompiled table). Tests assert this stays 0 for shipped shaders.
    /// </summary>
    internal static int GlslcFallbackCount;

    /// <summary>
    /// Deterministic FNV-1a 64-bit hash over the UTF-8 bytes of the source. Unlike
    /// <see cref="string.GetHashCode()"/> (per-process randomized) this is stable across
    /// processes/builds, so the build-time precompiled table can be keyed by it.
    /// </summary>
    internal static ulong StableHash(string s)
    {
        ulong h = 14695981039346656037UL;
        foreach (byte b in System.Text.Encoding.UTF8.GetBytes(s)) { h ^= b; h *= 1099511628211UL; }
        return h;
    }

    /// <summary>
    /// Compile a GLSL compute shader source string to SPIR-V bytes.
    /// Served from the precompiled table when present, else from the in-process cache,
    /// else compiled via glslc (and cached).
    /// </summary>
    public static byte[] Compile(string glslSource, string entryPoint = "main")
    {
        ulong key = StableHash(glslSource);

        // 1. Precompiled, committed table — the runtime path for every shipped shader.
        if (ShadersPrecompiled.TryGet(key, out var precompiled))
            return precompiled;

        // 2. In-process cache (for repeated misses, e.g. ad-hoc test shaders).
        lock (s_cache)
        {
            if (s_cache.TryGetValue(key, out var cached))
                return cached;
        }

        // 3. glslc fallback — only reached for sources outside the precompiled table.
        System.Threading.Interlocked.Increment(ref GlslcFallbackCount);

        var glslcPath = FindGlslc()
            ?? throw new FileNotFoundException("glslc not found. Install the Vulkan SDK.");

        // Write source to temp file, compile to SPIR-V
        var tempGlsl = Path.GetTempFileName() + ".comp";
        var tempSpv = Path.GetTempFileName() + ".spv";
        try
        {
            File.WriteAllText(tempGlsl, glslSource);

            var psi = new ProcessStartInfo
            {
                FileName = glslcPath,
                Arguments = $"\"{tempGlsl}\" -o \"{tempSpv}\" --target-env=vulkan1.3 -O",
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            };

            using var proc = Process.Start(psi)!;
            var stderr = proc.StandardError.ReadToEnd();
            proc.WaitForExit(30_000);

            if (proc.ExitCode != 0)
                throw new InvalidOperationException($"glslc failed:\n{stderr}");

            var spirv = File.ReadAllBytes(tempSpv);
            lock (s_cache)
                s_cache[key] = spirv;
            return spirv;
        }
        finally
        {
            File.Delete(tempGlsl);
            File.Delete(tempSpv);
        }
    }

    private static string? FindGlslc()
    {
        // Check PATH
        var pathDirs = Environment.GetEnvironmentVariable("PATH")?.Split(Path.PathSeparator) ?? [];
        foreach (var dir in pathDirs)
        {
            var candidate = Path.Combine(dir, "glslc.exe");
            if (File.Exists(candidate)) return candidate;
            candidate = Path.Combine(dir, "glslc");
            if (File.Exists(candidate)) return candidate;
        }

        // Check common Vulkan SDK locations on Windows
        var vulkanSdk = Environment.GetEnvironmentVariable("VULKAN_SDK");
        if (vulkanSdk is not null)
        {
            var candidate = Path.Combine(vulkanSdk, "Bin", "glslc.exe");
            if (File.Exists(candidate)) return candidate;
        }

        return null;
    }
}
