<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpInference.Core\SharpInference.Core.csproj" />
    <ProjectReference Include="..\SharpInference.Cpu\SharpInference.Cpu.csproj" />
  </ItemGroup>
</Project>
