using System.Globalization;
using System.Reflection;
using System.Text;
using SharpInference.Vulkan;

// SpirvGen — regenerates src/SharpInference.Vulkan/Shaders.Precompiled.g.cs.
//
// Reflects every `internal const string` GLSL shader on SharpInference.Vulkan.Shaders,
// compiles each to SPIR-V via ShaderCompiler.Compile, computes the deterministic
// ShaderCompiler.StableHash of the exact const value, and emits a switch keyed by that hash
// returning a static readonly byte[] per shader. The file is rewritten wholesale, so stale
// entries are dropped. Note: Compile consults the linked-in table first, so unchanged
// shaders return their committed bytes (identical) while an edited shader's new hash misses
// and re-runs glslc — producing SPIR-V that matches what the runtime would compile.

// Always recompile from GLSL source — never reuse the (possibly stale) committed table —
// so regeneration picks up shader edits and glslc-flag changes.
ShaderCompiler.BypassPrecompiled = true;

string repoRoot = FindRepoRoot();
string outPath = Path.Combine(repoRoot, "src", "SharpInference.Vulkan", "Shaders.Precompiled.g.cs");

// Reflect the GLSL shader const strings, sorted by name for stable diffs.
var shaders = typeof(Shaders)
    .GetFields(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)
    .Where(f => f.IsLiteral && f.FieldType == typeof(string))
    .Select(f => (Name: f.Name, Source: (string)f.GetRawConstantValue()!))
    .OrderBy(s => s.Name, StringComparer.Ordinal)
    .ToList();

if (shaders.Count == 0)
{
    Console.Error.WriteLine("SpirvGen: no shader const strings found on SharpInference.Vulkan.Shaders.");
    return 1;
}

// Compile each shader and check for stable-hash collisions (would silently lose entries).
// A handful of shaders (SgemmBf16, SgemmFp8) require GLSL extensions that the bundled
// shaderc/glslc does not support; the Vulkan backend already wraps their pipeline creation
// in try/catch and falls back, so we record them as skipped (with their hash) rather than
// abort. ANY OTHER compile failure is fatal — that would be a real regression.
var entries = new List<(string Name, ulong Hash, byte[] Spirv)>(shaders.Count);
var skipped = new List<(string Name, ulong Hash, string Reason)>();
var seenHashes = new Dictionary<ulong, string>();
foreach (var (name, source) in shaders)
{
    ulong hash = ShaderCompiler.StableHash(source);
    if (seenHashes.TryGetValue(hash, out var other))
    {
        Console.Error.WriteLine($"SpirvGen: stable-hash collision between '{name}' and '{other}' (0x{hash:X16}).");
        return 1;
    }
    seenHashes[hash] = name;

    byte[] spirv;
    try
    {
        spirv = ShaderCompiler.Compile(source);
    }
    catch (Exception ex) when (IsUnsupportedExtension(ex.Message, out var ext))
    {
        Console.WriteLine($"SpirvGen: skipping '{name}' — glslc lacks extension {ext} (backend falls back at runtime).");
        skipped.Add((name, hash, ext));
        continue;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"SpirvGen: glslc failed compiling '{name}': {ex.Message}");
        return 1;
    }

    if (spirv.Length == 0 || spirv.Length % 4 != 0 ||
        !(spirv[0] == 0x03 && spirv[1] == 0x02 && spirv[2] == 0x23 && spirv[3] == 0x07))
    {
        Console.Error.WriteLine($"SpirvGen: '{name}' did not produce valid SPIR-V (len={spirv.Length}).");
        return 1;
    }

    entries.Add((name, hash, spirv));
}

string generated = Emit(entries, skipped);
File.WriteAllText(outPath, generated);

Console.WriteLine($"SpirvGen: wrote {entries.Count} precompiled + {skipped.Count} skipped " +
    $"= {entries.Count + skipped.Count} total ({generated.Length / 1024} KB) to {outPath}");
return 0;

// glslc's "extension not supported" message names the extension; capture it so the
// generated file (and tests) record exactly which shaders are intentionally absent.
static bool IsUnsupportedExtension(string message, out string ext)
{
    ext = "";
    const string marker = "extension not supported: ";
    int idx = message.IndexOf(marker, StringComparison.Ordinal);
    if (idx < 0) return false;
    int start = idx + marker.Length;
    int end = start;
    while (end < message.Length && (char.IsLetterOrDigit(message[end]) || message[end] == '_')) end++;
    ext = message.Substring(start, end - start);
    return ext.Length > 0;
}

static string Emit(List<(string Name, ulong Hash, byte[] Spirv)> entries,
    List<(string Name, ulong Hash, string Reason)> skipped)
{
    // Precompute the 256 byte→hex strings once instead of ToString("x2") per byte
    // (the SPIR-V blobs total ~150 KB → hundreds of thousands of formats otherwise).
    var hex = new string[256];
    for (int i = 0; i < 256; i++) hex[i] = i.ToString("x2", CultureInfo.InvariantCulture);

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/> — regenerated by tools/SpirvGen (scripts/gen-spirv.ps1). DO NOT EDIT.");
    sb.AppendLine("// Maps the FNV-1a 64-bit ShaderCompiler.StableHash of each GLSL shader source in");
    sb.AppendLine("// Shaders.cs to its precompiled SPIR-V, so the published NativeAOT binary needs no");
    sb.AppendLine("// glslc at runtime. This file is committed and compiles like any other source (no");
    sb.AppendLine("// glslc needed to BUILD); glslc is only needed by the dev-run generator.");
    sb.AppendLine("namespace SharpInference.Vulkan;");
    sb.AppendLine();
    sb.AppendLine("internal static class ShadersPrecompiled");
    sb.AppendLine("{");
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Number of distinct precompiled shader entries in the table. Used by tests to");
    sb.AppendLine("    /// catch a partial/stale table.");
    sb.AppendLine($"    /// </summary>");
    sb.AppendLine($"    internal static int Count => {entries.Count};");
    sb.AppendLine();
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Shaders intentionally NOT precompiled because the generator's glslc lacks the");
    sb.AppendLine("    /// required GLSL extension. The Vulkan backend wraps these in try/catch and falls");
    sb.AppendLine("    /// back at runtime, so they miss this table by design. (Count + SkippedShaders.Length");
    sb.AppendLine("    /// must equal the total number of Shaders consts.)");
    sb.AppendLine("    /// </summary>");
    if (skipped.Count == 0)
    {
        sb.AppendLine("    internal static readonly string[] SkippedShaders = System.Array.Empty<string>();");
    }
    else
    {
        sb.AppendLine("    internal static readonly string[] SkippedShaders =");
        sb.AppendLine("    {");
        foreach (var (name, _, reason) in skipped)
            sb.AppendLine($"        \"{name}\", // requires {reason}");
        sb.AppendLine("    };");
    }
    sb.AppendLine();
    sb.AppendLine("    /// <summary>");
    sb.AppendLine("    /// Look up precompiled SPIR-V by the FNV-1a 64-bit stable hash of its GLSL source.");
    sb.AppendLine("    /// </summary>");
    sb.AppendLine("    internal static bool TryGet(ulong h, out byte[] spirv)");
    sb.AppendLine("    {");
    sb.AppendLine("        switch (h)");
    sb.AppendLine("        {");
    for (int i = 0; i < entries.Count; i++)
        sb.AppendLine($"            case 0x{entries[i].Hash:X16}UL: spirv = _s{i}; return true; // {entries[i].Name}");
    sb.AppendLine("            default: spirv = System.Array.Empty<byte>(); return false;");
    sb.AppendLine("        }");
    sb.AppendLine("    }");
    sb.AppendLine();
    for (int i = 0; i < entries.Count; i++)
    {
        sb.AppendLine($"    // {entries[i].Name} ({entries[i].Spirv.Length} bytes)");
        sb.Append($"    private static readonly byte[] _s{i} = {{ ");
        var spv = entries[i].Spirv;
        for (int b = 0; b < spv.Length; b++)
        {
            if (b > 0) sb.Append(',');
            sb.Append("0x");
            sb.Append(hex[spv[b]]);
        }
        sb.AppendLine(" };");
    }
    sb.AppendLine("}");
    return sb.ToString();
}

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "SharpInference.slnx")))
            return dir.FullName;
        dir = dir.Parent;
    }
    throw new InvalidOperationException("SpirvGen: could not locate repo root (SharpInference.slnx) from " + AppContext.BaseDirectory);
}
